version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deploy
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/stopApp.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/startApp.sh
      timeout: 60
      runas: root