DROP TABLE TBL_MEMBER;
CREATE TABLE TBL_MEMBER (
  MEMBER_NO NUMBER PRIMARY KEY,
  MEMBER_ID VARCHAR2(13),
  MEMBER_PWD VARCHAR2(255),
  MEMBER_NAME VARCHAR2(20),
  EMAIL VARCHAR2(50),
  BIRTHDAY VARCHAR2(8),
  GENDER CHAR(1),
  PHONE VARCHAR2(20),
  ADDRESS VARCHAR2(255),
  ENROLL_DATE DATE DEFAULT SYSDATE,
  MODIFY_DATE DATE DEFAULT SYSDATE,
  MEMBER_ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
  STATUS VARCHAR2(1) DEFAULT 'Y'
);
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO;