name: CI

# 어떤 브랜치를 체크할 지 설정
on:
  push:
    branches:
      - master # deploy branche가 push 됬을때 
    
# Workflow 설정
jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
        distribution: 'adopt'
        cache: maven
    - name: add Application.properties
      run:
        touch ./src/main/webapp/config/config.properties
      shell: bash
      
    - name: copy config.properties
      run:
        echo "${{ secrets.PROPERTIES }}" > ./src/main/webapp/config/config.properties
      shell: bash

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true -B package --file pom.xml
      
    - name: move build files
      run: mv ./target/ROOT.war ./

    - name: zip build files
      run: zip -r $GITHUB_SHA.zip ./appspec.yml ./ROOT.war ./scripts


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    - name: Upload to S3
      run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./$GITHUB_SHA.zip s3://${{ secrets.AWS_S3_BUCKET }}/$GITHUB_SHA.zip


    - name: deploy
      run: | 
        aws deploy create-deployment \
        --deployment-config-name CodeDeployDefault.AllAtOnce \
        --application-name ${{ secrets.AWS_CODEDEPLOY_NAME }} \
        --deployment-group-name ${{ secrets.AWS_CODEDEPLOY_GROUP }} \
        --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=$GITHUB_SHA.zip
